### PR TITLE
gitmodule url changed to ssh/git and matplotlib version pinned

### PR DESCRIPTION
**Pull request by asaxton**

### CODE REVIEW

**Comment by asaxton** [comment]
I want the ssh/git urls in the .gitmodules set to the ssh/git urls so that we can develop code in the submodule in place and push changes to the submodules remote. 

The docker build workflow is failing because of no permission to pull with ssh/git urls

I didn't think we needed ssh rsa keys generated when simply cloning a repo?

**Comment by abodeuis** [comment]
ssh urls require you to have a ssh key setup configured to use. There is a way to do this with submodules but every user that wants to clone/use the repo would need to set a submodule config up with their own ssh credentials. This would just be another barrier to entry that I don't think we want or need. I would advise sticking to HTTPS.

**Comment by robkooper** [comment]
@abodeuis is right, as can be seen from the failed build.

**Comment by asaxton** [comment]
Okay, I understand your concerns. I still think there's a discussion to be had about this. But we'll table it for now.

**Comment by abodeuis** [comment]
Closing for inactivity as we decided that this method won't work.

**Pull request closed without merging**
