### PR TITLE
Cdr output

### PR DESCRIPTION
**Pull request by abodeuis**
Starting the pull request for getting the CDR Output branch on main. CDR Output currently doesn't have the code for amqp and will need to have that added.

### CODE REVIEW

**Comment by asaxton** [comment]
@abodeuis 

This PR contains too many changes. Our strategy of this PR will be to separate it into 3 PR's 1) make old models obsolete 2) Support `drab-volcano` 3) Multi-process e.g. multi gpu.

Beginning with 1). 

Step 1) Create new clone and make sure main is checked out to the latest commit.
Step 2) Create branch `git checkout -b obsolete/models`
Step 3) cherry pick commit from this branch (`cdr_output`) by running the following
```git cherry-pick a378efd7bdcce817be3aa292ea8779f79eae7e05```

*There will be a merge conflict*. I was able to merge it, but I want you too. After resolving the merge conflict you will notice that `flat_iceberg` and `vectorization` are submodules that are also removed. These are modules that are critical to the mission of this project. If they need to get refactored or deployed in another way, it was not discussed with the team.

Please perform Step 1-3) above. In step 3 make sure `flat_iceberg` and `vectorization` are included in the supported submodules. If there is a technical reason they are not, articulate that in the PR for `obsolete/models`

**Comment by abodeuis** [comment]
From the pipeline perspective everything should be in order now. Need to perform the merge of main into cdr_output before this branch will actually be ready to go into main.

**Comment by abodeuis** [comment]
@asaxton  Flat_iceberg and Vectorization submodules are not used anymore. Jiahua had to switch to using one submodule so that his custom package is not installed twice. The vectorization submodule is no longer used as its functions got wrapped up into the cmaas_utils package.

**Comment by asaxton** [comment]
`flat-iceberg` is still a supported model, make sure it’s include in this PR. 

With regard to vectorization, I see it now in the requirements.txt. That’s great it got moved into a proper module. We’ll test against cog `34c138e939e929e90a6d066d316939690c693c6d2c6d2e696f692712f08d61cd` before release (This is the COG Justin visualized our output for us).

**Comment by abodeuis** [comment]
flat-iceberg is still supported and works just fine if you test the pipeline. The flat-iceberg model uses code from the drab_volcano submodule, as does drab-volcano model. As mentioned above this was due to Jiahua needing to have his custom code that supports those models installed as a single package that comes from the drab-volcano submodule.

**Comment by abodeuis** [comment]
I did tests on all of the models from a fresh git clone in local and amqp mode all models are working besides blaring_foundry. Seems to be an issue with the code in the submodule, will probably need @xiyuez2 to help with that. Docker seems to build fine. Otherwise getting close to being able to merge.
Things that still need to be done before merge to main :
- Write up some patch notes for what is different to pipeline users
- AMQP mode needs code to route maps that encounter errors to the error queue
- Testing amqp mode
- Testing docker container

**Comment by asaxton** [comment]
I'm not seeing raster output anymore. I ran

```
python pipeline.py -v \
--data /projects/bbym/saxton/MockValData/validation \
--output ./output \
--legends /projects/bbym/saxton/MockValData/validation \
--feedback ./feedback --log ./logs/log.log \
--model flat_iceberg \
--validation /projects/bbym/saxton/MockValData/validation_labels
```
for both `flat_iceberg` and `golden_muscat` to output directory only has 
```
KY_WestFranklin_cdr.json  KY_WestFranklin.gpkg  OR_Carlton_cdr.json  OR_Carlton.gpkg
```

**Pull request merged**
